print('Hi, who are you?')
myName = input ()
print('Ah, hello, ' + myName + '.')
print('What should we do today?')
direction = input ()
print('Oh, I dont really want to ' + direction + ' today.')
print('...Got anything else?')
twiceover = input ()
print('Yeah! Maybe we could ' + twiceover + '! Cmon then!')
